In [2]:
import numpy as np

In [13]:
x = np.array([1,2,3,4,5])

In [14]:
x

array([1, 2, 3, 4, 5])

In [15]:
np.split(x,[3,5])

[array([1, 2, 3]), array([4, 5]), array([], dtype=int32)]

In [17]:
m = np.arange(16)

In [18]:
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
x= m.reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [22]:
np.vsplit(x,[2])

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [25]:
np.hsplit(x,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [3]:
m = np.random.randint(10,size=(4,5))
m

array([[8, 0, 8, 5, 3],
       [0, 4, 6, 4, 9],
       [0, 1, 6, 5, 5],
       [9, 2, 4, 3, 0]])

In [5]:
m[0:2,0:3]

array([[8, 0, 8],
       [0, 4, 6]])

In [1]:
import pandas as pd

In [7]:
a = np.array([2,12,32,22,45])

In [13]:
seri = pd.Series(a)

In [9]:
seri

0     2
1    12
2    32
3    22
4    45
dtype: int32

In [14]:
seri[0:3]

0     2
1    12
2    32
dtype: int32

In [15]:
seri2 = pd.Series([121,200,150,99], index = ["reg","loj","cart","rf"])
seri2

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [17]:
seri2["reg":"loj"]

reg    121
loj    200
dtype: int64

In [8]:
l = [1,2,39,32,21]
l

[1, 2, 39, 32, 21]

In [5]:
pd.DataFrame(l, columns = ["degisken_ismi"])

degisken_ismi
0              1
1              2
2             39
3             32
4             21

In [7]:
m = np.arange(1,10).reshape((3,3))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
pd.DataFrame(m, columns = ["var1","var2","var3"])

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [12]:
#df isimlendirmeleri

In [14]:
df = pd.DataFrame(m, columns = ["var1","var2","var3"])
df.head()

var1  var2  var3
0     1     2     3
1     4     5     6
2     7     8     9

In [15]:
df.columns

Index(['var1', 'var2', 'var3'], dtype='object')

In [16]:
df.columns = ("deg1","deg2","deg3")

In [18]:
df.head()

deg1  deg2  deg3
0     1     2     3
1     4     5     6
2     7     8     9

In [20]:
type(df)

pandas.core.frame.DataFrame

In [21]:
df.axes

[RangeIndex(start=0, stop=3, step=1),
 Index(['deg1', 'deg2', 'deg3'], dtype='object')]

In [22]:
df.ndim

2

In [23]:
df.shape

(3, 3)

In [24]:
df.size

9

In [25]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
type(df.values)

numpy.ndarray

In [28]:
df.tail(1)

deg1  deg2  deg3
2     7     8     9

In [29]:
#numpy arrayı uzerinden de bir dataframe kolayca oluşturabiliriz

In [30]:
a = np.array([1,2,3,4,5])

In [31]:
pd.DataFrame(a,columns = ["deg1"])

deg1
0     1
1     2
2     3
3     4
4     5

* Pandas da Eleman işlemleri

In [43]:
s1 = np.random.randint(10,size = 5)
s2 = np.random.randint(10,size = 5)
s3 = np.random.randint(10,size = 5)

In [41]:
sozluk = {"var1" : s1, "var2" : s2, "var3" : s3}

In [44]:
df = pd.DataFrame(sozluk)
df

var1  var2  var3
0     3     7     4
1     6     1     5
2     0     1     5
3     2     1     3
4     2     2     9

In [46]:
df[0:2]

var1  var2  var3
0     3     7     4
1     6     1     5

In [48]:
df.size

15

In [53]:
df[1::2]

var1  var2  var3
1     6     1     5
3     2     1     3

In [54]:
df.index

RangeIndex(start=0, stop=5, step=1)

In [57]:
df.index = ["a","b","c","d","e"]
df

var1  var2  var3
a     3     7     4
b     6     1     5
c     0     1     5
d     2     1     3
e     2     2     9

In [80]:
#df["c":"e"]

+ silme işlemi

In [75]:
# df.drop("a",axis = 0)

* kalıcı olarak silmek istersek

In [1]:
#df.drop("a",axis = 0,inplace = True )